### ISSUE TITLE
Suggest current file path delimiter on windows

### ISSUE THREAD

**Issue by Joe5** [Trudko/advanced-new-file#10] opened 2015-02-21 15:11 UTC
Package is correctly suggesting directory location however it ends with wrong delimiter. Generated location looks something like this `web\jade\partials/`. The problem is in the last `/` which breaks the suggestions. Removing it and hitting tab or changing the suggested path to `web\jade\partials/\` fixes the issue.

**Comment by Trudko** [comment] 2015-02-24 18:20
@Joe5 thank your reporting the issue I will take a look at it this week.

**Comment by Joe5** [comment] 2015-02-25 13:49
@Trudko No problem.

**Comment by Trudko** [comment] 2015-02-26 14:30
what OS are you on?

**Comment by Joe5** [comment] 2015-02-26 18:59
Currently I am using Linux however the problem occurs under Windows (7).

**Comment by Trudko** [comment] 2015-02-26 19:54
Can you please provide version of Atom , the package and maybe even some code which I can reproduce this on ? When I run advanced new file command on this package everything seems work normally. I've tried this on Windows 8 and Ubuntu.

**Comment by Joe5** [comment] 2015-02-27 15:47
Latest Atom and latest version of the package. It was broken in Atom 182 as well (the time when I created this topic). Before this package I was using the "parent" package (fancy new file) and that package worked correctly.

**Comment by Trudko** [comment] 2015-02-27 16:48
Can you please help me reproduce the problem ? I can't do it what are the step to reproduce and what code do you use? For example if you download package code can you reproduce it with?

**Comment by Joe5** [comment] 2015-02-27 17:31
I could try but I am not really sure how can I help you to reproduce it. The files opened has nothing to do with it. I have tried to open multiple folders and it works the same every time. I have also tried to open the package code as you suggested and the result was the same.

Steps to reproduce the problem for me are just hitting `ctrl+alt+n` or hitting `ctrl+shift+p` and search for command to open the plugin menu. In the package settings I have set it to `suggest current file path` and `show files in auto complete` however file suggestions has no impact on this problem (i've tried to disable this).

There is no error or warning in the console.

I guess that you fetch from some method what is the directory separator and use that in the package. Maybe you could force ending separator to be the same as directory separator? But I don't like this approach since it's kinda hacky... Another option could be to add some field in the package settings that would give user option to specify the separator and use that with fall back / default generated in current version. But again this is not that grat way... it's more of a workaround than propper fix.

**Comment by Trudko** [comment] 2015-03-16 12:11
Hi, sorry for responding late I was focusing on other things. I am still unable to reproduce this. I've checked the code and I am using [path.sep](https://nodejs.org/api/path.html#path_path_sep) in the code. Maybe I am missing something.

**Comment by Joe5** [comment] 2015-03-17 06:32
Hello, no problem I understand... I know nothing about Node.js, literally however I do know a little from CoffeeScript. I've looked at the source code of your package and found the bug.

There is hard coded `/` separator at the end of the suggested path. I've tried to tweak it a bit and it fixed the problem for me.

When I find some free time I will try to make my first pull request ever. You should test it first I have no idea if would work on other systems but it should work just fine.

**Comment by Trudko** [comment] 2015-03-17 07:24
What's the line?

**Comment by Joe5** [comment] 2015-03-17 18:10
It was on 3 lines. One of them was 223.

I wanted to send you that pull request with my changes however when I forked your rep the source code was different than what was installed on Atom. Basically it already contained that concatenation of `path.sep` instead of `'/'` so there is nothing to change as it is already fixed.

I still have no idea how is it even possible that the source code here is different than what I had installed in Atom. I remember that I even reinstalled the package... Strange.

**Comment by Trudko** [comment] 2015-03-17 19:49
Seems like you had somehow old version of package :) Ok I am closing the issue :)

**Closed by Trudko** 2015-03-17 19:49 UTC

**Comment by Joe5** [comment] 2015-03-18 06:16
Nope the version is `"version": "0.3.3",` straight from package.json. But how it is even possible that it is different that I have no idea.

**Comment by Trudko** [comment] 2015-03-18 07:29
It will remain mystery from now :)

**Comment by Joe5** [comment] 2015-03-18 07:59
Yep it's not worth the time investment unless someone else experience this.
